#!/usr/bin/ruby
# 
# This file contains a collection of system event classes. System events are the
# events which the MUES::Engine uses directly, and generally concerned with
# low-level subsystems and Engine functionality itself.
#
# The event classes defined in this file are:
#
# [MUES::SystemEvent]
# 	An abstract system event class.
#
# [MUES::SocketEvent]
# 	An abstract socket event class. Events which deal with socket connections,
# 	disconnections, etc. are derived from this class.
#
# [MUES::SocketConnectEvent]
# 	An event class that is created when a connection is accepted on the
# 	listening socket.
#
# [MUES::LogEvent]
# 	An event class used to add an entry to the log.
#
# [MUES::TickEvent]
# 	An event class used to mark the passage of time, trigger other scheduled or
# 	interval-driven events, and provide the hosted Environments with a
# 	"heartbeat".
#
# [MUES::EngineShutdownEvent]
# 	An event class used to instruct the MUES::Engine to shut down.
#
# [MUES::GarbageCollectionEvent]
# 	An event that instructs the Engine to start a garbage-collection cycle.
#
# [MUES::ReconfigEvent]
# 	An event that notifies the Engine that an item in the server configuration
# 	has changed.
#
# [MUES::ExceptionEvent]
# 	An event that contains an exception object of some sort.
#
# [MUES::UntrappedExceptionEvent]
# 	An event which is generated if a subsystem of the MUES lets an exception
# 	propagated into the EventQueue.
#
# [MUES::CallbackEvent]
# 	An event class which encapsulates a callback of some kind.
#
# [MUES::ThreadShutdownEvent]
# 	An event type which is generated by the supervisor thread of the
# 	MUES::EventQueue when it is scaling back the number of worker threads which
# 	are running.
#
# [MUES::UntrappedSignalEvent]
# 	An event which is generated when an untrapped  signal is caught.
# 
# == Synopsis
# 
#   require "mues/events/SystemEvents"
# 
# == Rcsid
# 
# $Id: systemevents.rb,v 1.7 2002/05/16 03:53:19 deveiant Exp $
# 
# == Authors
# 
# * Michael Granger <ged@FaerieMUD.org>
# 
#:include: COPYRIGHT
#
#---
#
# Please see the file COPYRIGHT for licensing details.
#

require "socket"

require "mues"
require "mues/Exceptions"
require "mues/events/BaseClass"


module MUES

	#################################################################
	###	A B S T R A C T   E V E N T   C L A S S E S
	#################################################################

	### An abstract base system event class. It is derived from the MUES::Event
	### class.
	class SystemEvent < Event ; implements MUES::AbstractClass
	end


	### An abstract socket event class. Events which deal with socket
	### connections, disconnections, etc. are derived from this class. It
	### derives from the MUES::SystemEvent class.
	class SocketEvent < SystemEvent ; implements MUES::AbstractClass
		attr_accessor	:socket

		### Initialize a new SocketEvent with the specified Socket object.
		def initialize( aSocket ) # :notnew:
			checkType( aSocket, TCPSocket )
			raise ArgumentError, "Socket is not connected" if aSocket.closed?

			@socket = aSocket
			super()
		end
	end



	#####################################################################
	###	C O N C R E T E   E V E N T   C L A S S E S
	#####################################################################

	### An event class that is created when a connection is accepted on the
	### listening socket. It is a derivative of MUES::SocketEvent.
	class SocketConnectEvent < SocketEvent
	end


	### An event class used to add an entry to the log. It derives from the
	### MUES::SystemEvent class.
	class LogEvent < SystemEvent

		# The log message
		attr_reader :message

		# The log "severity" level
		attr_reader :severity


		# Create and return a new LogEvent with the specified <tt>severity</tt>
		# (which must be one of <tt>"debug", "info", "notice", "error", "crit",
		# or "fatal") and +message+ parts, which will be <tt>join</tt>ed with
		# the empty string.
		def initialize( severity, *message )
			if ( severity =~ %r{(debug|info|notice|error|crit|fatal)} )
				@severity = $1
			else
				@severity = "info"
				message.unshift( severity )
			end

			@message = if message.empty? then "[Mark]" else message.join(" ") end
			super()
		end

		### Returns a stringified version of the event
		def to_s
			return "%s: (%s) %s" % [
				super(),
				@severity,
				@message
			]
		end

	end


	### An event class used to mark the passage of time, trigger other scheduled
	### or interval-driven events, and provide the hosted Environments with a
	### "heartbeat". It derives from the MUES::SystemEvent class.
	class TickEvent < SystemEvent

		# The sequence number of the tick
		attr_accessor :tickNumber

		### Create and return a new TickEvent with the sequence number specified
		### by <tt>tickNumber</tt>, which must be a Fixnum.
		def initialize( tickNumber )
			checkType( tickNumber, Fixnum )

			@tickNumber = tickNumber
			super()
		end

	end

	### An event class used to instruct the MUES::Engine to shut down. It
	### derives from the MUES::SystemEvent class.
	class EngineShutdownEvent < SystemEvent

		# The agent of the shutdown (ie., the User or system requesting the
		# shutdown).
		attr_accessor :agent

		# Create and return a new EngineShutdownEvent with the specified object
		# registered as the agent.
		def initialize( anObject )
			@agent = anObject
			super()
		end
	end


	### An event that instructs the Engine to start a garbage-collection
	### cycle. It derives from the MUES::SystemEvent class.
	class GarbageCollectionEvent < SystemEvent
	end

	### An event that notifies the Engine that an item in the server
	### configuration has changed. It derives from the MUES::SystemEvent class.
	class ReconfigEvent < SystemEvent
	end


	### An event that contains an exception object of some sort. It derives from
	### the MUES::SystemEvent class.
	class ExceptionEvent < SystemEvent

		# The exception object
		attr_accessor :exception

		### Create and return a new ExceptionEvent with the specified +exception+.
		def initialize( exception )
			checkType( exception, ::Exception, Interrupt )

			@exception = exception
			super()
		end
	end


	### An event which is generated if a subsystem of the MUES lets an exception
	### propagated into the EventQueue. It derives from the MUES::ExceptionEvent
	### class.
	class UntrappedExceptionEvent < ExceptionEvent

		### Stringify the event
		def to_s
			return "%s: %s\n\t%s" % [
				super(),
				@exception.message,
				@exception.backtrace.join( "\n\t" )
			]
		end
	end


	### An event class which encapsulates a callback of some kind. It is used
	### when a callback should be executed asynchronously, such as a repeating
	### or scheduled call to a timer or heartbeat function that operates at a
	### different interval than the Engine's TickEvent. It derives from the
	### MUES::SystemEvent class.
	class CallbackEvent < SystemEvent

		# The callback (a Proc or Method object).
		attr_accessor :callback

		# The callback's argument array.
		attr_accessor :args

		### Create and return a new CallbackEvent with the specified +callback+
		### (a Proc or a Method object), which will be called with the specified
		### arguments.
		def initialize( callback, *args )
			checkType( callback, Proc, Method )
			@callback = callback
			@args = args
			super()
		end
	end


	### An event type which is generated by the supervisor thread of the
	### MUES::EventQueue when it is scaling back the number of worker threads
	### which are running. It derives from the MUES::SystemEvent class.
	class ThreadShutdownEvent < SystemEvent
	end


	### An event which is generated when an untrapped signal is caught. It
	### derives from the MUES::ExceptionEvent class.
	class UntrappedSignalEvent < ExceptionEvent
	end


end # module MUES

