--- 
rubyforge_project: mues
project_requirements: {}

project_pubdir: /usr/local/www/public/code
project_description: A multi-threaded, event-driven Internet game environment server.
rubyforge_group: deveiate
project_pubhost: deveiate
project_homepage: http://deveiate.org/projects/MUES
project_dependencies: 
  bunny: ">= 0.4.4"
project_summary: The Multi-User Environment Server
project_name: MUES
version_file: mues.rb
additional_pkgfiles: 
- server/**/*
dev_dependencies: {}

authors: 
  Martin Chase: stillflame@FaerieMUD.org
  Michael Granger: ged@FaerieMUD.org
  Dave McCorkhill: scotus@FaerieMUD.org
post_install_message: ""
