--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code
project_pubhost: deveiate
project_homepage: http://deveiate.org/projects/MUES
rubyforge_group: deveiate
project_requirements: {}

project_description: A multi-threaded, event-driven Internet game environment server.
project_dependencies: 
  pluginfactory: ">= 1.0.4"
  bunny: ">= 0.5.2"
project_summary: The Multi-User Environment Server
version_file: mues.rb
additional_pkgfiles: 
- server/**/*
dev_dependencies: {}

authors: 
  Martin Chase: stillflame@FaerieMUD.org
  Michael Granger: ged@FaerieMUD.org
  Dave McCorkhill: scotus@FaerieMUD.org
post_install_message: ""
project_name: MUES
rubyforge_project: mues
