---
general:
  server name: Experimental MUD
  server description: An experimental MUES server
  server admin: MUES ADMIN <muesadmin@localhost>
  root dir: .
  includePath:
    - server
    - server/lib
  motd: |
    MUES Server Command Shell:
    /help for help
    /quit to disconnect
    /shutdown to halt the server (admin privileges required)
engine:
  tick length: 1.0
  exception stack size: 10
  debug level: 0
  eventqueue:
    minworkers: 5
    maxworkers: 50
    threshold: 2
    safelevel: 2
  privileged eventqueue:
    minworkers: 2
    maxworkers: 5
    threshold: 1.5
    safelevel: 1
  objectstore:
    backend: BerkeleyDB
    memorymanager: Null
  listeners:
    shell:
      name: telnet
      kind: telnet
      filterDebug: 5
      params:
        useWrapper: false
        banner: >
          --- #{general.serverName} ---------------

          #{general.serverDescription}

          Contact: #{general.serverAdmin}

        bindAddress: 0.0.0.0
        bindPort: 4848
        loginsession:
          kind: ''
          params:
            userPrompt: "Username: "
            passPrompt: "Password: "
    console:
      name: console
      kind: console
      filterDebug: 5
      params:
        loginsession:
          kind: ''
          params:
            userPrompt: "Console: "
            passPrompt: "Password (echoed): "
login:
  banner: |
    --- %general/server name% ---------------
    %general/server description%
    Contact: *poc
  questionnaire: login
  params:
    userPrompt: 'Username: '
    passPrompt: 'Password: '
    maxTries: 3
    timeout: 600
logging:
  MUES:
    level: debug
    outputters: ''
  MUES::Engine:
    level: debug
    outputters:
      file: server/log/server.log
environments:
  envPath:
    - server/environments
  autoload:
    "null":
      kind: "Null"
      params: {}
      description: A testing environment without any surroundings.
