---
general:
  server name: Experimental MUD
  server description: An experimental MUES server
  server admin: MUES ADMIN <muesadmin@localhost>
  root dir: .
  includePath:
    - server
    - server/lib
  motd: |
    MUES Server Command Shell:
    /help for help
    /quit to disconnect
    /shutdown to halt the server (admin privileges required)
engine:
  tick length: 1.0
  exception stack size: 10
  debug level: 0
  eventqueue:
    minworkers: 5
    maxworkers: 50
    threshold: 2
    safelevel: 2
  privileged eventqueue:
    minworkers: 2
    maxworkers: 5
    threshold: 1.5
    safelevel: 1
  objectstore:
    backend: BerkeleyDB
    memorymanager: Null
  listeners:
    shell:
      kind: telnet
      params:
        useWrapper: false
        banner: >
          --- #{general.serverName} ---------------

          #{general.serverDescription}

          Contact: #{general.serverAdmin}


        questionnaire:
          name: login
          params:
            userPrompt: "Username: "
            passPrompt: "Password: "
        bindAddress: 0.0.0.0
        bindPort: 4848
    console:
      kind: console
      params:
        questionnaire:
          name: login
          params:
            userPrompt: "Console: "
            passPrompt: "Password (echoed): "
login:
  banner: |
    --- %general/server name% ---------------
    %general/server description%
    Contact: *poc
  questionnaire: login
  params:
    username prompt: 'Username: '
    password prompt: 'Password: '
logging:
  MUES:
    level: debug
    outputters: ''
  MUES::Engine:
    level: debug
    outputters:
      file: server/log/server.log
environments:
  envPath:
    - server/environments
  autoload:
    "null":
      kind: "Null"
      params: {}
      description: A testing environment without any surroundings.
commandshell:
  - shell class: MUES::CommandShell
  - params:
    reload interval: 50
    default prompt: 'mues> '
    command prefix: /
